[package]
name = "camunda-client"
version = "0.1.0"
authors = ["Maximb <sprayrules@gmail.com>"]
edition = "2018"

[dependencies]

log = "*"
futures = "0.1.21"
tokio = "*"
hyper = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
hyper-multipart-rfc7578 = "0.2.0-alpha2"
mio_httpc = "*"
